### ISSUE TITLE
BAT file issues nuke the install directory

### ISSUE THREAD

**Issue by TheKins** [MKCAMK/G-MODE-Archives-translations#1]
Hi,

For some reason, the current BAT files have a nasty proclivity of deleting the _Data directory instead of copying the patched files over or whatever, citing the error "can't move new file to old directory "(path data001.tmp)" ERROR! call import system api error! errno: 2, No such file or directory".

I was able to apply the patches manually via the command line by having them export the patched files to a seperate folder that I renamed to replace the Data folder...

`ddp_doj_dx.1.3.exe -f "F:\Steam\steamapps\common\GmodeArchivesPlus_DodonpachiDX\DodonpachiDX_Data" -X "F:\Steam\steamapps\common\GmodeArchivesPlus_DodonpachiDX\DodonpachiDX_Data2"`

...but there's probably a better way than that. :V Is this a problem with the BAT, or on my end?

**Comment by MKCAMK** [comment]
Definitely not on your end. This is the biggest problem I have right now. 

I have observed it happening both with BAT and without it. Although in my case it has never deleted _Data — the patch was applied correctly, despite the error message. I even thought of suppressing the message, but thought that it would be a good idea to leave it in case of a wider issue. Seems I was right!

Are you positive that it actually deleted _Data folder?

It might be a patcher issue? I will have to write a custom patcher to have greater control over it anyway.

**Comment by TheKins** [comment]
> Are you positive that it actually deleted _Data folder?

Well, after the patch ran, the _Data folder no longer existed in the game directory, the game refused to run citing its lack of existence, and I had to use Steam's Verify Game Files feature to redownload them. Seems pretty much like what happened?

**Comment by MKCAMK** [comment]
Damn! That is quite serious then!

I think as an emergency measure I will modify the BAT to have the patcher create a new folder, and then replace it separately.

Thank you very much for the report! Immense help!

**Comment by MKCAMK** [comment]
The patcher will now output to a separate folder, and the BAT will take care of moving it in instead.
