### ISSUE TITLE
Interested in contributing 

### ISSUE THREAD

**Issue by dadjumper** [MKCAMK/G-MODE-Archives-translations#4]
Hi there! Sorry if this is a weird way to get in contact but I'm not sure where else to do so.
Would you be able to provide contact info (e.g. discord) for people working on these patches? 
I'm interested in contributing my translation skills to the Gregory Horror Show G-Mode game.

**Comment by MKCAMK** [comment]
No, no – that is perfect.

If I could ask you to send me an e-mail at
mkca.dev@gmail.com
then I will respond with contact details we could use to get you involved.
