### ISSUE TITLE
Request: Aegis: The First Mission

### ISSUE THREAD

**Issue by SirGamers** [MKCAMK/G-MODE-Archives-translations#5]
Someone has already done all the translation work, you would just have to do the modding
[Translation here](https://www.reddit.com/r/PERSoNA/comments/dxwq6g/aegis_the_first_mission_full_translation_pdf_the/)
[Game page here](https://store.steampowered.com/app/2850150/GMODE_3__THE_FIRST_MISSION/)
“It would be so awesome… it would be so cool…”
P.S. maybe make 2 versions of the mod? Aegis version and Aigis version?

**Comment by MKCAMK** [comment]
We are in fact aware of this translated script existing, and have taken a look at it.

If we end up releasing anything for this game, you will be able to find it on this here repository.

Thank you for reaching out to us!

**Comment by Glitxhhh** [comment]
when is it possible aegis translation will release? it seems progress is very slow considering no other translations have released in like a year? is there possibly a discord where interested users can see progress or possibly help out?

**Comment by MKCAMK** [comment]
We do not give any information here about patches we may or may not be working on. This repository is purely for already released patches.

All I can say for _Aigis: The First Mission_ is that you may want to keep checking this repository from time to time, just in case.

If you are desperate to know more, feel free to send me an e-mail! If you click on my user name, you can see the address on my profile.
